[build]
  base    = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "http://holdet.syndikatet.eu/*"
to = "https://holdet.syndikatet.eu/:splat"
status = 301
force = true
